[package]
authors.workspace = true
edition.workspace = true
name = "lustrefs-exporter"
version.workspace = true

[dependencies]
axum = {workspace = true, features = ["http2"]}
clap = {workspace = true, features = ["derive", "env", "wrap_help", "string"]}
compact_str = {version = "0.8", features = ["smallvec"]}
lustre_collector.path = "../lustre-collector"
num-traits = "0.2"
opentelemetry = { workspace = true, features = ["metrics"] }
opentelemetry-prometheus = { version = "0.29.0" }
opentelemetry_sdk = { workspace = true, features = ["metrics", "rt-tokio"] }
prometheus = "0.14"
prometheus_exporter_base = {version = "1.4.0"}
regex = {version = "1", default-features = false, features = ["perf", "std", "perf-dfa-full"]}
serde = {version = "1", features = ["derive"]}
thiserror = "1"
tokio = {workspace = true, features = [
  "rt-multi-thread",
  "macros",
  "process",
]}
tokio-stream = "0.1.15"
tower = {version = "0.4.13", features = ["timeout", "load-shed", "limit"]}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
tracing.workspace = true

[dev-dependencies]
combine.workspace = true
const_format = "0.2.32"
include_dir.workspace = true
insta.workspace = true
serde_json = "1"
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }

[lib]
bench = false

[[bin]]
name = "lustrefs-exporter"
path = "src/main.rs"
bench = false

[[bench]]
name = "jobstats"
harness = false
