[package]
authors.workspace = true
edition.workspace = true
name = "lustrefs-exporter"
version.workspace = true

[dependencies]
clap = {workspace = true, features = ["derive", "env", "wrap_help", "string"]}
lustre_collector.path = "../lustre-collector"
num-traits = "0.2.14"
prometheus = "0.13.3"
prometheus_exporter_base = {git = "https://github.com/RDruon/prometheus_exporter_base", features = ["hyper_server"]}
tokio = {version = "1.27", features = [
  "rt-multi-thread",
  "macros",
  "process",
]}
tracing-subscriber = {workspace = true, features = ["env-filter"]}
tracing.workspace = true

[dev-dependencies]
combine.workspace = true
include_dir.workspace = true
insta.workspace = true
serde_json = "1"
