[package]
authors.workspace = true
edition.workspace = true
name = "lustrefs-exporter"
version.workspace = true

[dependencies]
clap = {workspace = true, features = ["derive", "env", "wrap_help", "string"]}
lustre_collector.path = "../lustre-collector"
num-traits = "0.2.14"
prometheus = "0.13.3"
futures = "0.3.30"
axum-streams = { version = "0.18", features=["text"] }
axum = "0.7.5"
prometheus-client = "0.22.3"
prometheus_exporter_base = {version = "1.4.0", features = ["hyper_server"]}
tokio = {version = "1.27", features = [
  "rt-multi-thread",
  "macros",
  "process",
]}
tokio-stream = "0.1.15"
tracing-subscriber = {workspace = true, features = ["env-filter"]}
tracing.workspace = true
serde_json = "1"

[dev-dependencies]
combine.workspace = true
include_dir.workspace = true
insta.workspace = true
serde_json = "1"
