[package]
authors.workspace = true
edition.workspace = true
name = "lustrefs_exporter"
version = "0.3.0"

[dependencies]
clap = {workspace = true, features = ["derive", "env", "wrap_help", "string"]}
lustre_collector.path = "../lustre-collector"
num-traits = "0.2.14"
prometheus = "0.13.3"
prometheus_exporter_base = {version = "1.4.0", features = ["hyper_server"]}
tokio = {version = "1.27", features = [
  "rt-multi-thread",
  "macros",
  "process",
]}
tracing.workspace = true
tracing-subscriber = {workspace = true, features = ["env-filter"]}

[dev-dependencies]
combine = "=4.6.7"
insta.workspace = true
include_dir.workspace = true
serde_json = "1"
