[package]
authors.workspace = true
edition.workspace = true
name = "lustrefs-exporter"
version.workspace = true

[dependencies]
axum = {workspace = true, features = ["http2"]}
clap = {workspace = true, features = ["derive", "env", "wrap_help", "string"]}
compact_str = {version = "0.8", features = ["smallvec"]}
lustre_collector.path = "../lustre-collector"
num-traits = "0.2"
prometheus = "0.13"
prometheus_exporter_base = {version = "1.4.0"}
regex = {version = "1", default-features = false, features = ["perf", "std", "perf-dfa-full"]}
thiserror = "1"
tokio = {workspace = true, features = [
  "rt-multi-thread",
  "macros",
  "process",
]}
tokio-stream = "0.1.15"
tracing-subscriber = {workspace = true, features = ["env-filter"]}
tracing.workspace = true

[dev-dependencies]
const_format = "0.2.32"
combine.workspace = true
include_dir.workspace = true
insta.workspace = true
serde_json = "1"
