#!/bin/bash

# Copyright (c) 2025 DDN. All rights reserved.
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file.

if [[ "$*" == 'net show -v 4' ]]; then
    cat $(dirname "$0")/../fixtures/lnetctl_net_show.txt
elif [[ "$*" == 'stats show' ]]; then
    cat $(dirname "$0")/../fixtures/lnetctl_stats.txt
else
    echo "lnetctl params not covered: $*"
fi
